### ISSUE TITLE
consider make zigzag explicitly instead of implicit apply it on signed

### ISSUE THREAD

**Issue by shuoli84** [dermesser/integer-encoding-rs#14]
Zigzag and varint are two separate thing, though for signed integer, it is better to use both. But there are cases to apply only varint on signed integer. One example is thrift's compact protocol's sequence number field. It stated explicitly should be encoded as var int, though it is signed i32.

**Comment by dermesser** [comment]
I don't fully understand -- in that case, is the encoded integer always 5 bytes long, as the most-significant bit (sign bit) needs to be encoded? Frankly, this doesn't sound very useful to me.

However, if there is a use case, as you say, I would be open to accepting this feature.

**Comment by shuoli84** [comment]
In my understanding, it is only 5 bytes long if it is negative. refer to golang's impl: https://github.com/apache/thrift/blob/master/lib/go/thrift/compact_protocol.go#L138 and compact spec: https://github.com/apache/thrift/blob/master/doc/specs/thrift-compact-protocol.md.

**Comment by dermesser** [comment]
That makes sense. Would you be up for a PR, or should I take a look at how to best extend the existing API?

**Comment by shuoli84** [comment]
Do you have any idea on how to refactor the existing API? It seems as a breaking change.

**Comment by allengeorge** [comment]
I think this issue can be closed.

It's true: for signed integers variable-length coding and zigzag encoding are separate concerns. That said, I don't know how many places actually _use_ them separately. Thrift only does so for sequence numbers, and I don't know why.

I believe there's a straightforward workaround for users of `integer-encoding-rs` to get the behaviour we want. From my understanding, casting an `i###` to a `u###` in Rust doesn't change the memory representation of the primitive. This means that we can:

1. first cast a signed int to an unsigned one
2. use `write_varint` (which will _not_ zigzag encode, since the type being written is unsigned)

We then do the reverse on the reading side.

**Comment by shuoli84** [comment]
That is what I did to work around this.

I think the problem is the fn name didn't specify the differences, and var and zigzag are two things in both thrift & grpc spec. Maybe rename the fn name to make it clear is an easy fix?

**Comment by allengeorge** [comment]
@shuoli84 Is there a case where the gRPC spec does **not** zigzag encode negative numbers?

**Comment by dermesser** [comment]
> @shuoli84 Is there a case where the gRPC spec does **not** zigzag encode negative numbers?

that's the reason why I didn't think twice about always combining varint+zigzag: Encoding one-complement's negative numbers as varints even increases size, as the MSB needs to always be encoded, making varint essentially useless.

**Comment by mrwiggles** [comment]
> that's the reason why I didn't think twice about always combining varint+zigzag: Encoding one-complement's negative numbers as varints even increases size, as the MSB needs to always be encoded, making varint essentially useless.

Yeah. My take is that unless there are _multiple_ cases where people are using varints and zigzag-encoding separately it's not worth it to change the API of this crate. I've already changed Thrift itself to workaround this, and I'd rather keep this crate's API straightforward and avoid changing it for one usecase.

**Comment by allengeorge** [comment]
> that's the reason why I didn't think twice about always combining varint+zigzag: Encoding one-complement's negative numbers as varints even increases size, as the MSB needs to always be encoded, making varint essentially useless.

Yeah. My take is that unless there are multiple cases where people are using varints and zigzag-encoding separately it's not worth it to change the API of this crate. I've already changed Thrift itself to workaround this, and I'd rather keep this crate's API straightforward and avoid changing it for one usecase.
