### ISSUE TITLE
Consider a new release?

### ISSUE THREAD

**Issue by shuoli84** [dermesser/integer-encoding-rs#17]
tokio has been upgraded to 1.0, consider release a new version? So crates depending on integer-encoding can update their tokio version. :)

**Comment by dermesser** [comment]
Can you check again? I've uploaded v3.0 to crates.io a few days ago :)
![image](https://user-images.githubusercontent.com/1042327/104087727-10f9a180-5262-11eb-8aff-f8c6d6bca5d2.png)

**Comment by shuoli84** [comment]
awesome!
