### ISSUE TITLE
Panic during read

### ISSUE THREAD

**Issue by jkcclemens** [dermesser/integer-encoding-rs#3]
At [this line](https://github.com/dermesser/integer-encoding-rs/blob/master/src/reader.rs#L27), I'm encountering a panic when `i` becomes `10` and then the index is invalid. Should probably return an `Err` when `i` becomes that large, rather than indirectly cause a panic.

**Comment by dermesser** [comment]
definitely. I hope 8eb722f fixes it. Another commit on top of that also protects the varint decoder from overly long bytestrings.

**Comment by jkcclemens** [comment]
Awesome! Thank you very much.
