### ISSUE TITLE
!assert in encode_var

### ISSUE THREAD

**Issue by cemoktra** [dermesser/integer-encoding-rs#38]
I would suggest replacing `!assert` with `!debug_assert` in those places, as the call to `required_space` has a huge impact on performance:

![image](https://github.com/dermesser/integer-encoding-rs/assets/15634263/4c5cd0ab-6a10-4a42-8f25-446da46c8697)

**Comment by dermesser** [comment]
that's true, we can rely on the bounds checking when writing to `dst`.
