### ISSUE TITLE
Handling varint decode errors

### ISSUE THREAD

**Issue by SOF3** [dermesser/integer-encoding-rs#9]
If all bytes of the slice have MSB set, the library assumes the last slice does not have the MSB set, and silently truncates.

Furthermore, if the value of the varint overflows, it silently drops the overflowing bits.

These are malformed representations and should have error reported.

**Comment by dermesser** [comment]
thank you, I've seen the issue! I will take a look when I have a bit of time.

**Comment by dermesser** [comment]
I hope I will soon get a chance to fix this.
